### ISSUE TITLE
Reconnecting supported?

### ISSUE THREAD

**Issue by vimalmistry** [ConsoleTVs/AdonisWebsok#2]
Is this package reconnect after disconnect? 
Or other way how to keep eye on connection state?

**Comment by ConsoleTVs** [comment]
You can play around onError method to act and reconnect

**Comment by fweinaug** [comment]
I get an exception when calling connect with an onError callback. Seems like the signature needs to change (Stream uses `Function onError`) or am I doing something wrong? 

```
Invalid argument(s): handleError callback must take either an Object (the error), or both an Object (the error) and a StackTrace

StackTrace:
#0      _BufferingStreamSubscription.onError (dart:async/stream_impl.dart:152:7)
#1      new _BufferingStreamSubscription (dart:async/stream_impl.dart:115:10)
#2      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:123:9)
#3      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:93:16)
#4      _ForwardingStream.listen (dart:async/stream_pipe.dart:88:12)
#5      Websok.listen (package:websok/websok.dart:78:27)
#6      AdonisWebsok.connect (package:adonis_websok/adonis_websok.dart:143:19)
```

**Comment by nhtlquan** [comment]
> I get an exception when calling connect with an onError callback. Seems like the signature needs to change (Stream uses `Function onError`) or am I doing something wrong?
> 
> ```
> Invalid argument(s): handleError callback must take either an Object (the error), or both an Object (the error) and a StackTrace
> 
> StackTrace:
> #0      _BufferingStreamSubscription.onError (dart:async/stream_impl.dart:152:7)
> #1      new _BufferingStreamSubscription (dart:async/stream_impl.dart:115:10)
> #2      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:123:9)
> #3      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:93:16)
> #4      _ForwardingStream.listen (dart:async/stream_pipe.dart:88:12)
> #5      Websok.listen (package:websok/websok.dart:78:27)
> #6      AdonisWebsok.connect (package:adonis_websok/adonis_websok.dart:143:19)
> ```

Me too

**Comment by fweinaug** [comment]
I created a PR to fix this in the Websok project: https://github.com/ConsoleTVs/Websok/pull/1

**Comment by fweinaug** [comment]
I just created a PR to fix the exception: #3
